"""Create table Cursos

Revision ID: 3bad706e9ac5
Revises: cf820cf557a4
Create Date: 2024-08-15 21:24:18.619954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bad706e9ac5'
down_revision = 'cf820cf557a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estudante', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['id_estudante'], ['estudantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricoes')
    # ### end Alembic commands ###
